#!/usr/bin/env python3
import argparse
import json

from typing import Dict, Any


def read_manifest(fname: str):
    with open(fname, mode="r", encoding="utf-8") as jsonfile:
        return json.load(jsonfile)


def diff_curl_sources(adata, bdata):
    if adata == bdata:
        return {}

    if adata is None:
        return {"b-only": bdata}

    if bdata is None:
        return {"a-only": adata}

    aitems = adata["items"]
    bitems = bdata["items"]

    diff: Dict[str, Any] = {}

    for aid, aitem in aitems.items():
        if bitem := bitems.get(aid):
            if aitem != bitem:
                # same package, different options (url, gpg check)
                diffitems = diff.get("items", {})
                diffitems[aid] = {"a": aitem, "b": bitem}
                diff["items"] = diffitems
        else:
            # package in a doesn't exist in b
            diffitems = diff.get("items", {})
            a_only = diffitems.get("a-only", {})
            a_only[aid] = aitem
            diffitems["a-only"] = a_only
            diff["items"] = diffitems

    return diff


def diff_package_names(adata, bdata):
    diff = []

    apkgs = [data["url"].split("/")[-1] for data in adata["items"].values()]
    bpkgs = [data["url"].split("/")[-1] for data in bdata["items"].values()]

    for apkg, bpkg in zip(sorted(apkgs), sorted(bpkgs)):
        if apkg != bpkg:
            diff.append(f"{apkg} -- {bpkg}")

    return diff


def diff_sources(adata, bdata):
    diff = {}

    diff["org.osbuild.curl"] = diff_curl_sources(
        adata.get("org.osbuild.curl"),
        bdata.get("org.osbuild.curl"),
    )

    diff["packages"] = diff_package_names(
        adata.get("org.osbuild.curl"),
        bdata.get("org.osbuild.curl"),
    )

    return diff


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("a")
    parser.add_argument("b")
    args = parser.parse_args()

    file_a = args.a
    file_b = args.b

    adata = read_manifest(file_a)
    bdata = read_manifest(file_b)

    diff = diff_sources(adata["manifest"]["sources"], bdata["manifest"]["sources"])
    print("\n".join(diff["packages"]))


if __name__ == "__main__":
    main()
